# Generated by Django 4.2 on 2026-02-22 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFiscalEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ambiente_sefaz', models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', max_length=1, verbose_name='Ambiente SEFAZ')),
                ('serie_nfe', models.CharField(default='001', max_length=3, verbose_name='Série NF-e')),
                ('serie_nfce', models.CharField(default='001', max_length=3, verbose_name='Série NFC-e')),
                ('serie_nfse', models.CharField(default='001', max_length=3, verbose_name='Série NFS-e')),
                ('csc_id_nfce', models.CharField(blank=True, max_length=10, null=True, verbose_name='CSC ID NFC-e')),
                ('csc_token_nfce', models.CharField(blank=True, max_length=255, null=True, verbose_name='CSC Token NFC-e (Criptografado)')),
            ],
            options={
                'verbose_name': 'Configuração Fiscal da Empresa',
                'verbose_name_plural': 'Configurações Fiscais da Empresa',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('cnae_principal', models.CharField(max_length=7, verbose_name='CNAE Principal')),
                ('cnae_secundarios', models.JSONField(blank=True, null=True, verbose_name='CNAEs Secundários')),
                ('regime_tributario', models.CharField(choices=[('SN', 'Simples Nacional'), ('SNEI', 'Simples Nacional - Excesso de Ingresso'), ('LP', 'Lucro Presumido'), ('LR', 'Lucro Real'), ('LA', 'Lucro Arbitrado'), ('MEI', 'Microempreendedor Individual'), ('ENTE', 'Entidade Imune ou Isenta')], max_length=5, verbose_name='Regime Tributário')),
                ('porte', models.CharField(blank=True, choices=[('MEI', 'Microempreendedor Individual'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('MEDIO', 'Empresa de Médio Porte'), ('GRANDE', 'Grande Empresa')], max_length=10, null=True, verbose_name='Porte da Empresa')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('ibge', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código IBGE do Município')),
                ('certificado_digital_pfx', models.FileField(blank=True, null=True, upload_to='certificados/', verbose_name='Certificado Digital (.pfx)')),
                ('certificado_senha', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha do Certificado (Criptografada)')),
                ('certificado_data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade do Certificado')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cnpj'], name='empresas_em_cnpj_fe5b68_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nome_fantasia'], name='empresas_em_nome_fa_dfb6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ativo'], name='empresas_em_ativo_236150_idx'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalempresa',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_fiscal', to='empresas.empresa'),
        ),
    ]
