# Generated by Django 4.2 on 2026-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscalempresa',
            name='proximo_numero_nfce',
            field=models.BigIntegerField(default=1, verbose_name='Próximo Número NFC-e'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalempresa',
            name='proximo_numero_nfe',
            field=models.BigIntegerField(default=1, verbose_name='Próximo Número NF-e'),
        ),
        migrations.AddField(
            model_name='configuracaofiscalempresa',
            name='proximo_numero_nfse',
            field=models.BigIntegerField(default=1, verbose_name='Próximo Número NFS-e'),
        ),
    ]
