# Generated by Django 4.2 on 2026-02-22 02:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_lancamento', models.DateField(verbose_name='Data do Lançamento')),
                ('historico', models.TextField(verbose_name='Histórico')),
                ('tipo_lancamento', models.CharField(choices=[('SIMPLES', 'Simples (Débito e Crédito)'), ('COMPOSTO', 'Composto (Múltiplos Débitos/Créditos)')], default='SIMPLES', max_length=10, verbose_name='Tipo de Lançamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Lançamento Contábil',
                'verbose_name_plural': 'Lançamentos Contábeis',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='PartidaLancamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_partida', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='Tipo de Partida')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('historico_complementar', models.TextField(blank=True, null=True, verbose_name='Histórico Complementar')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='financeiro.planocontas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabil.lancamentocontabil')),
            ],
            options={
                'verbose_name': 'Partida de Lançamento',
                'verbose_name_plural': 'Partidas de Lançamento',
                'unique_together': {('lancamento', 'conta_contabil', 'tipo_partida')},
            },
        ),
    ]
