version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.example
    ports:
      - "5433:5432" # Expose for local access if needed

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: gunicorn backend.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A backend.config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.example
    depends_on:
      - db
      - redis
      - backend

  celery_beat:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A backend.config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file:
      - .env.example
    depends_on:
      - db
      - redis
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules # Anonymous volume to hide host node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_API_PROXY_TARGET=http://backend:8000
      - VITE_ALLOWED_HOSTS=localhost,127.0.0.1,backend,9bf2-170-0-212-221.ngrok-free.app
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_HOST_PORT:-80}:80"
    depends_on:
      - backend
      - frontend


volumes:
  postgres_data:
