# Generated by Django 4.2 on 2026-02-22 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Conta')),
                ('tipo_conta', models.CharField(choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança'), ('APL', 'Aplicação Financeira'), ('CX', 'Caixa Interno')], default='CC', max_length=3, verbose_name='Tipo de Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Atual')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conta Bancária/Caixa',
                'verbose_name_plural': 'Contas Bancárias/Caixa',
                'unique_together': {('empresa', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=20, verbose_name='Código da Conta')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Conta')),
                ('tipo_conta', models.CharField(choices=[('RC', 'Receita'), ('DS', 'Despesa'), ('AT', 'Ativo'), ('PA', 'Passivo'), ('PL', 'Patrimônio Líquido')], max_length=2, verbose_name='Tipo da Conta')),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_contas', to='financeiro.planocontas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_movimentacao', models.DateField(default=datetime.date.today, verbose_name='Data da Movimentação')),
                ('tipo_movimentacao', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('T', 'Transferência')], max_length=1, verbose_name='Tipo de Movimentação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.contabancaria')),
                ('conta_contabil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='financeiro.planocontas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'ordering': ['-data_movimentacao', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_liquidacao', models.DateField(blank=True, null=True, verbose_name='Data de Liquidação')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PARCIAL', 'Paga/Recebida Parcialmente'), ('PAGA_RECEBIDA', 'Paga/Recebida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('parcela_atual', models.IntegerField(default=1, verbose_name='Parcela Atual')),
                ('total_parcelas', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('juros', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Desconto')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Recebido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_receber', to='cadastros.cliente')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_receber_contabil', to='financeiro.planocontas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_liquidacao', models.DateField(blank=True, null=True, verbose_name='Data de Liquidação')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PARCIAL', 'Paga/Recebida Parcialmente'), ('PAGA_RECEBIDA', 'Paga/Recebida'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('parcela_atual', models.IntegerField(default=1, verbose_name='Parcela Atual')),
                ('total_parcelas', models.IntegerField(default=1, verbose_name='Total de Parcelas')),
                ('juros', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Juros')),
                ('multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Multa')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Desconto')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Pago')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar_contabil', to='financeiro.planocontas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_a_pagar', to='cadastros.fornecedor')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
    ]
