# Generated by Django 4.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_perfilpermissao_perfil"),
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilpermissao",
            name="portal_cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_clientes",
                to="intake.portalcliente",
            ),
        ),
    ]
