# Generated by Django 4.2 on 2026-02-22 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Local')),
                ('tipo_local', models.CharField(choices=[('CD', 'Centro de Distribuição'), ('LOJA', 'Loja/Varejo'), ('ARM', 'Armazém'), ('PRAT', 'Prateleira'), ('OUTRO', 'Outro')], default='ARM', max_length=5, verbose_name='Tipo de Local')),
                ('endereco_completo', models.TextField(blank=True, null=True, verbose_name='Endereço Completo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Local de Estoque',
                'verbose_name_plural': 'Locais de Estoque',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_movimentacao', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE', 'Ajuste de Estoque'), ('INVENTARIO', 'Inventário')], max_length=15, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Quantidade')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('local_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_estoque', to='estoque.localestoque', verbose_name='Local de Destino')),
                ('local_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque', to='estoque.localestoque', verbose_name='Local de Origem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='LoteEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Lote')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Quantidade em Lote')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_armazenados', to='estoque.localestoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Lote de Estoque',
                'verbose_name_plural': 'Lotes de Estoque',
                'unique_together': {('empresa', 'produto', 'local_estoque', 'codigo_lote')},
            },
        ),
        migrations.CreateModel(
            name='InventarioEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inventario', models.DateField(default=datetime.date.today, verbose_name='Data do Inventário')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('local_estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='estoque.localestoque', verbose_name='Local Inventariado')),
            ],
            options={
                'verbose_name': 'Inventário de Estoque',
                'verbose_name_plural': 'Inventários de Estoque',
                'unique_together': {('empresa', 'local_estoque', 'data_inventario')},
            },
        ),
    ]
