# Generated by Django 4.2 on 2026-02-22 01:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('chave_acesso', models.CharField(blank=True, max_length=44, null=True, unique=True, verbose_name='Chave de Acesso')),
                ('protocolo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Protocolo de Autorização/Cancelamento')),
                ('numero', models.BigIntegerField(verbose_name='Número da NF')),
                ('serie', models.CharField(max_length=3, verbose_name='Série')),
                ('modelo', models.CharField(default='55', max_length=2, verbose_name='Modelo do Documento Fiscal')),
                ('tipo_nf', models.CharField(choices=[('1', 'NF-e (Modelo 55)'), ('2', 'NFC-e (Modelo 65)')], max_length=1, verbose_name='Tipo de NF')),
                ('finalidade', models.CharField(choices=[('1', 'NF-e Normal'), ('2', 'NF-e Complementar'), ('3', 'NF-e de Ajuste'), ('4', 'Devolução de Mercadoria')], max_length=1, verbose_name='Finalidade da Emissão')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('data_saida_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída/Entrada')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de Autorização'), ('PROCESSANDO', 'Processando Autorização'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada'), ('PROCESSAMENTO', 'Em Processamento (Evento)')], default='RASCUNHO', max_length=20, verbose_name='Status da NF')),
                ('destinatario_nome', models.CharField(max_length=255, verbose_name='Nome/Razão Social Destinatário')),
                ('destinatario_documento', models.CharField(max_length=14, verbose_name='CPF/CNPJ Destinatário')),
                ('destinatario_ie', models.CharField(blank=True, max_length=20, null=True, verbose_name='IE Destinatário')),
                ('destinatario_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Destinatário')),
                ('destinatario_cep', models.CharField(max_length=8, verbose_name='CEP Destinatário')),
                ('destinatario_logradouro', models.CharField(max_length=255, verbose_name='Logradouro Destinatário')),
                ('destinatario_numero', models.CharField(max_length=10, verbose_name='Número Destinatário')),
                ('destinatario_complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento Destinatário')),
                ('destinatario_bairro', models.CharField(max_length=100, verbose_name='Bairro Destinatário')),
                ('destinatario_municipio', models.CharField(max_length=100, verbose_name='Município Destinatário')),
                ('destinatario_uf', models.CharField(max_length=2, verbose_name='UF Destinatário')),
                ('destinatario_ibge', models.CharField(blank=True, max_length=7, null=True, verbose_name='IBGE Município Destinatário')),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total dos Produtos')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total do Desconto')),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total do Frete')),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total do Seguro')),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Outras Despesas')),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total ICMS')),
                ('valor_icms_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total ICMS ST')),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total IPI')),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total PIS')),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total COFINS')),
                ('valor_total_nf', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total da NF')),
                ('modalidade_frete', models.CharField(choices=[('0', 'Por conta do emitente'), ('1', 'Por conta do destinatário'), ('2', 'Por conta de terceiros'), ('3', 'Transporte próprio por conta do emitente'), ('4', 'Transporte próprio por conta do destinatário'), ('9', 'Sem ocorrência de transporte')], default='9', max_length=1, verbose_name='Modalidade do Frete')),
                ('xml_autorizado', models.FileField(blank=True, null=True, upload_to='nfe/xmls/', verbose_name='XML Autorizado')),
                ('xml_cancelamento', models.FileField(blank=True, null=True, upload_to='nfe/xmls/', verbose_name='XML Cancelamento')),
                ('pdf_danfe', models.FileField(blank=True, null=True, upload_to='nfe/danfes/', verbose_name='PDF DANFE')),
                ('codigo_retorno', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Retorno SEFAZ')),
                ('mensagem_retorno', models.TextField(blank=True, null=True, verbose_name='Mensagem de Retorno SEFAZ')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfe_transportadas', to='cadastros.fornecedor')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_descricao', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('produto_ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('produto_cest', models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST')),
                ('produto_cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('produto_ean', models.CharField(blank=True, max_length=14, null=True, verbose_name='EAN/GTIN')),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Unitário')),
                ('valor_desconto_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Desconto no Item')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('icms_cst_csosn', models.CharField(blank=True, max_length=3, null=True, verbose_name='ICMS CST/CSOSN')),
                ('icms_base_calculo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='ICMS BC')),
                ('icms_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ICMS Alíquota')),
                ('icms_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='ICMS Valor')),
                ('ipi_cst', models.CharField(blank=True, max_length=2, null=True, verbose_name='IPI CST')),
                ('ipi_base_calculo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='IPI BC')),
                ('ipi_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='IPI Alíquota')),
                ('ipi_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='IPI Valor')),
                ('pis_cst', models.CharField(blank=True, max_length=2, null=True, verbose_name='PIS CST')),
                ('pis_base_calculo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PIS BC')),
                ('pis_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='PIS Alíquota')),
                ('pis_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='PIS Valor')),
                ('cofins_cst', models.CharField(blank=True, max_length=2, null=True, verbose_name='COFINS CST')),
                ('cofins_base_calculo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='COFINS BC')),
                ('cofins_aliquota', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='COFINS Alíquota')),
                ('cofins_valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='COFINS Valor')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiscal.notafiscal')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.produto')),
            ],
            options={
                'verbose_name': 'Item da Nota Fiscal',
                'verbose_name_plural': 'Itens da Nota Fiscal',
            },
        ),
        migrations.CreateModel(
            name='EventoNotaFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_evento', models.CharField(choices=[('110110', 'Cancelamento'), ('110114', 'Carta de Correção'), ('110115', 'EPEC'), ('PROCESSAMENTO', 'Processamento de NF')], max_length=20, verbose_name='Tipo de Evento')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa/Texto')),
                ('xml_evento', models.FileField(blank=True, null=True, upload_to='nfe/eventos/', verbose_name='XML do Evento')),
                ('protocolo_retorno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Protocolo de Retorno')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fiscal.notafiscal')),
            ],
            options={
                'verbose_name': 'Evento da Nota Fiscal',
                'verbose_name_plural': 'Eventos da Nota Fiscal',
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['empresa', 'status'], name='fiscal_nota_empresa_3003e9_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['empresa', 'chave_acesso'], name='fiscal_nota_empresa_8bd6cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together={('empresa', 'numero', 'serie', 'tipo_nf')},
        ),
    ]
