# Generated by Django 4.2 on 2026-02-22 02:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cargo')),
                ('cbo', models.CharField(blank=True, max_length=7, null=True, verbose_name='CBO')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField(verbose_name='Competência (Mês/Ano)')),
                ('tipo_folha', models.CharField(choices=[('MENSAL', 'Mensal'), ('DECIMO_TERCEIRO', 'Décimo Terceiro'), ('FERIAS', 'Férias'), ('RESCISAO', 'Rescisão')], default='MENSAL', max_length=15, verbose_name='Tipo de Folha')),
                ('data_processamento', models.DateField(auto_now_add=True, verbose_name='Data de Processamento')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('PROCESSADA', 'Processada'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Folha de Pagamento',
                'verbose_name_plural': 'Folhas de Pagamento',
                'unique_together': {('empresa', 'competencia', 'tipo_folha')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)')], max_length=15, null=True, verbose_name='Estado Civil')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('ctps', models.CharField(blank=True, max_length=11, null=True, verbose_name='CTPS')),
                ('pis', models.CharField(blank=True, max_length=11, null=True, verbose_name='PIS')),
                ('titulo_eleitor', models.CharField(blank=True, max_length=12, null=True, verbose_name='Título de Eleitor')),
                ('reservista', models.CharField(blank=True, max_length=15, null=True, verbose_name='Certificado de Reservista')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco para Pagamento')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança')], max_length=20, null=True, verbose_name='Tipo de Conta')),
                ('dependentes', models.IntegerField(default=0, verbose_name='Número de Dependentes IRRF')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'unique_together': {('empresa', 'cpf')},
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('centro_custo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro de Custo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='HoleriteFuncionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('salario_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Salário Bruto')),
                ('valor_horas_extras_50', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Horas Extras 50%')),
                ('valor_horas_extras_100', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Horas Extras 100%')),
                ('outros_proventos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Outros Proventos')),
                ('total_proventos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Proventos')),
                ('desconto_inss', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Desconto INSS')),
                ('desconto_irrf', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Desconto IRRF')),
                ('desconto_fgts', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Desconto FGTS')),
                ('outros_descontos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Outros Descontos')),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Descontos')),
                ('liquido_receber', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Líquido a Receber')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('base_calculo_inss', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Base de Cálculo INSS')),
                ('base_calculo_irrf', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Base de Cálculo IRRF')),
                ('base_calculo_fgts', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Base de Cálculo FGTS')),
                ('pdf_holerite', models.FileField(blank=True, null=True, upload_to='holerites/', verbose_name='PDF do Holerite')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('folha_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holerites', to='folha.folhapagamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holerites', to='folha.funcionario')),
            ],
            options={
                'verbose_name': 'Holerite de Funcionário',
                'verbose_name_plural': 'Holerites de Funcionários',
                'unique_together': {('funcionario', 'folha_pagamento')},
            },
        ),
        migrations.CreateModel(
            name='ContratoTrabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'Pessoa Jurídica (Serviço)'), ('APRENDIZ', 'Aprendiz'), ('ESTAGIO', 'Estágio'), ('TEMPORARIO', 'Temporário')], max_length=15, verbose_name='Tipo de Contrato')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salário Base')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Contrato Ativo')),
                ('categoria_esocial', models.CharField(blank=True, choices=[('101', 'Empregado (exceto doméstico)'), ('102', 'Empregado Doméstico')], max_length=3, null=True, verbose_name='Categoria eSocial')),
                ('horas_extras_50', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Extras 50%')),
                ('horas_extras_100', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Extras 100%')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='folha.cargo')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='folha.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='folha.funcionario')),
            ],
            options={
                'verbose_name': 'Contrato de Trabalho',
                'verbose_name_plural': 'Contratos de Trabalho',
                'unique_together': {('funcionario', 'data_inicio')},
            },
        ),
    ]
