# Generated by Django 4.2 on 2026-02-22 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('folha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Celular/WhatsApp'),
        ),
        migrations.AddField(
            model_name='holeritefuncionario',
            name='data_envio_whatsapp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio WhatsApp'),
        ),
        migrations.AddField(
            model_name='holeritefuncionario',
            name='valor_dsr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor DSR sobre HE'),
        ),
        migrations.AddField(
            model_name='holeritefuncionario',
            name='whatsapp_enviado',
            field=models.BooleanField(default=False, verbose_name='Enviado por WhatsApp'),
        ),
        migrations.CreateModel(
            name='JustificativaPonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('tipo', models.CharField(choices=[('ATESTADO_MEDICO', 'Atestado Médico'), ('FALTA_JUSTIFICADA', 'Falta Justificada'), ('FALTA_NAO_JUSTIFICADA', 'Falta Não Justificada'), ('SUSPENSAO', 'Suspensão'), ('FERIAS', 'Férias'), ('LICENÇA_MATERNIDADE', 'Licença Maternidade/Paternidade'), ('TREINAMENTO', 'Treinamento/Cursos'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Justificativa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observação')),
                ('cid', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID')),
                ('crm_medico', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRM do Médico')),
                ('nome_medico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Médico')),
                ('documento', models.FileField(blank=True, null=True, upload_to='folha/justificativas/', verbose_name='Documento Comprobatório (PDF/Img)')),
                ('abona_ponto', models.BooleanField(default=True, verbose_name='Abona o Ponto (Não desconta)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='folha.funcionario')),
            ],
            options={
                'verbose_name': 'Justificativa de Ponto',
                'verbose_name_plural': 'Justificativas de Ponto',
            },
        ),
        migrations.CreateModel(
            name='ImportacaoPonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('arquivo', models.FileField(upload_to='folha/pontos/', verbose_name='Arquivo de Ponto')),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=15)),
                ('formato', models.CharField(default='CSV', max_length=20, verbose_name='Formato do Arquivo')),
                ('log_processamento', models.TextField(blank=True, null=True, verbose_name='Log de Processamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Importação de Ponto',
                'verbose_name_plural': 'Importações de Ponto',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFuncionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato de Trabalho'), ('ADITIVO', 'Aditivo Contratual'), ('TERMO_RESPONSABILIDADE', 'Termo de Responsabilidade'), ('OPCAO_VT', 'Opção de Vale Transporte'), ('FICHA_REGISTRO', 'Ficha de Registro'), ('OUTROS', 'Outros')], max_length=30, verbose_name='Tipo de Documento')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='folha/documentos/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='folha.funcionario')),
            ],
            options={
                'verbose_name': 'Documento de Funcionário',
                'verbose_name_plural': 'Documentos de Funcionários',
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data', models.DateField(verbose_name='Data do Registro')),
                ('entrada_1', models.TimeField(blank=True, null=True, verbose_name='Entrada 1')),
                ('saida_1', models.TimeField(blank=True, null=True, verbose_name='Saída 1')),
                ('entrada_2', models.TimeField(blank=True, null=True, verbose_name='Entrada 2')),
                ('saida_2', models.TimeField(blank=True, null=True, verbose_name='Saída 2')),
                ('total_horas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Total de Horas Trabalhadas')),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas Extras')),
                ('atrasos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Atrasos/Faltas (Horas)')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa/Ocorrência')),
                ('manual', models.BooleanField(default=False, verbose_name='Lançamento Manual')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='folha.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data'],
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
