# Generated by Django 4.2 on 2026-02-22 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('codigo_interno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Interno')),
                ('ean', models.CharField(blank=True, max_length=14, null=True, verbose_name='EAN/GTIN')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=7, null=True, verbose_name='CEST')),
                ('cfop_padrao', models.CharField(blank=True, max_length=4, null=True, verbose_name='CFOP Padrão')),
                ('origem', models.CharField(choices=[('0', 'Nacional'), ('1', 'Estrangeira - Importação Direta'), ('2', 'Estrangeira - Adquirida no Mercado Interno'), ('3', 'Nacional, Conteúdo de Importação > 40% e <= 70%'), ('4', 'Nacional, Processos Produtivos Básicos'), ('5', 'Nacional, Conteúdo de Importação <= 40%'), ('6', 'Estrangeira - Importação Direta, sem similar Nacional'), ('7', 'Estrangeira - Adquirida no Mercado Interno, sem similar Nacional'), ('8', 'Nacional, Conteúdo de Importação > 70%')], default='0', max_length=1, verbose_name='Origem')),
                ('cst_icms', models.CharField(blank=True, max_length=3, null=True, verbose_name='CST ICMS')),
                ('aliquota_icms', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alíquota ICMS (%)')),
                ('mva_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='MVA-ST (%)')),
                ('cst_ipi', models.CharField(blank=True, max_length=2, null=True, verbose_name='CST IPI')),
                ('aliquota_ipi', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alíquota IPI (%)')),
                ('cst_pis_cofins', models.CharField(blank=True, max_length=2, null=True, verbose_name='CST PIS/COFINS')),
                ('aliquota_pis', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alíquota PIS (%)')),
                ('aliquota_cofins', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Alíquota COFINS (%)')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço de Venda')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Estoque Mínimo')),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default=0.0, max_digits=15, verbose_name='Estoque Máximo')),
                ('controla_estoque', models.BooleanField(default=True, verbose_name='Controla Estoque')),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Líquido (kg)')),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Bruto (kg)')),
                ('largura', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Largura (cm)')),
                ('altura', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Altura (cm)')),
                ('profundidade', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Profundidade (cm)')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('nome_fantasia_apelido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia/Apelido')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('EX', 'Exterior')], default='PF', max_length=2, verbose_name='Tipo de Pessoa')),
                ('documento', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('indicador_ie', models.CharField(choices=[('1', 'Contribuinte ICMS'), ('2', 'Contribuinte Isento de Inscrição no Cadastro de Contribuintes do ICMS'), ('9', 'Não Contribuinte')], default='9', max_length=1, verbose_name='Indicador IE')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('ibge', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código IBGE do Município')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, choices=[('CC', 'Conta Corrente'), ('CP', 'Conta Poupança')], max_length=20, null=True, verbose_name='Tipo de Conta')),
                ('chave_pix', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('nome_fantasia_apelido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia/Apelido')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica'), ('EX', 'Exterior')], default='PF', max_length=2, verbose_name='Tipo de Pessoa')),
                ('documento', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('indicador_ie', models.CharField(choices=[('1', 'Contribuinte ICMS'), ('2', 'Contribuinte Isento de Inscrição no Cadastro de Contribuintes do ICMS'), ('9', 'Não Contribuinte')], default='9', max_length=1, verbose_name='Indicador IE')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('ibge', models.CharField(blank=True, max_length=7, null=True, verbose_name='Código IBGE do Município')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Limite de Crédito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'descricao'], name='cadastros_p_empresa_6c5954_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'ean'], name='cadastros_p_empresa_f585fb_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'ncm'], name='cadastros_p_empresa_75b1e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('empresa', 'codigo_interno')},
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('empresa', 'documento')},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'documento')},
        ),
    ]
