# Generated by Django 4.2 on 2026-02-22 02:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoFiscal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_obrigacao', models.CharField(choices=[('DARF', 'DARF (Documento de Arrecadação de Receitas Federais)'), ('PGDAS', 'PGDAS-D (Programa Gerador do Documento de Arrecadação do Simples Nacional)'), ('DAE', 'DAE (Documento de Arrecadação do eSocial)'), ('DAS_MEI', 'DAS-MEI (Documento de Arrecadação do Simples Nacional para o MEI)'), ('DIRF', 'DIRF (Declaração do Imposto de Renda Retido na Fonte)'), ('DCTF', 'DCTF (Declaração de Débitos e Créditos Tributários Federais)'), ('DEFIS', 'DEFIS (Declaração de Informações Socioeconômicas e Fiscais)'), ('GIA', 'GIA (Guia de Informação e Apuração do ICMS)'), ('DESTDA', 'DeSTDA (Declaração de Substituição Tributária, Diferencial de Alíquotas e Antecipação)'), ('ESOCIAL', 'eSocial'), ('EFD', 'EFD (Escrituração Fiscal Digital - ICMS/IPI e Contribuições)'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Tipo de Obrigação')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição Detalhada')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_envio_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Envio/Pagamento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ATRASADO', 'Atrasado'), ('PAGO', 'Pago'), ('ENVIADO', 'Enviado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('link_documento', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link para Documento/Comprovante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Obrigação Fiscal',
                'verbose_name_plural': 'Obrigações Fiscais',
                'ordering': ['data_vencimento'],
                'unique_together': {('empresa', 'tipo_obrigacao', 'data_vencimento')},
            },
        ),
    ]
