# Generated by Django 4.2 on 2026-04-09 14:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folha', '0002_funcionario_telefone_celular_and_more'),
        ('fiscal', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCompetencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField()),
                ('modulo', models.CharField(choices=[('FISCAL', 'Fiscal'), ('FOLHA', 'Folha'), ('FINANCEIRO', 'Financeiro'), ('CONTRATUAL', 'Contratual'), ('GERAL', 'Geral')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Checklist por Competência',
                'verbose_name_plural': 'Checklists por Competência',
                'ordering': ['-competencia', 'modulo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRecebido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('FISCAL', 'Fiscal'), ('FOLHA', 'Folha'), ('FINANCEIRO', 'Financeiro'), ('CONTRATUAL', 'Contratual'), ('GERAL', 'Geral')], max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('UPLOAD', 'Upload'), ('EMAIL', 'E-mail'), ('API', 'API'), ('MANUAL', 'Manual')], default='UPLOAD', max_length=20)),
                ('competencia', models.DateField()),
                ('arquivo', models.FileField(upload_to='intake/documentos/')),
                ('hash_arquivo', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('VALIDADO', 'Validado'), ('REPROVADO', 'Reprovado')], default='NOVO', max_length=20)),
                ('log_validacao', models.JSONField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='intake.checklistcompetencia')),
                ('contrato_trabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_intake', to='folha.contratotrabalho')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_intake', to='folha.funcionario')),
                ('nota_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_intake', to='fiscal.notafiscal')),
            ],
            options={
                'verbose_name': 'Documento Recebido',
                'verbose_name_plural': 'Documentos Recebidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PortalCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20, null=True)),
                ('recebe_alertas', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Portal do Cliente',
                'verbose_name_plural': 'Portais dos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_TRATAMENTO', 'Em tratamento'), ('RESOLVIDA', 'Resolvida')], default='ABERTA', max_length=20)),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='intake.checklistcompetencia')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='intake.documentorecebido')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
                'ordering': ['status', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LoteExportacaoQuestor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('competencia', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('EXPORTADO', 'Exportado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('arquivo_exportado', models.FileField(blank=True, null=True, upload_to='intake/questor/')),
                ('resumo', models.JSONField(blank=True, null=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Lote de Exportação Questor',
                'verbose_name_plural': 'Lotes de Exportação Questor',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='documentorecebido',
            name='portal_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='intake.portalcliente'),
        ),
        migrations.AddIndex(
            model_name='documentorecebido',
            index=models.Index(fields=['empresa', 'competencia'], name='intake_docu_empresa_7f8477_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorecebido',
            index=models.Index(fields=['empresa', 'status'], name='intake_docu_empresa_7a938d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentorecebido',
            index=models.Index(fields=['empresa', 'tipo_documento'], name='intake_docu_empresa_ed1959_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistcompetencia',
            unique_together={('empresa', 'competencia', 'modulo')},
        ),
    ]
